export const ADD_TO_DEMAND_ITEM = 'ADD_TO_DEMAND_ITEM';
export const ADD_TO_DEMAND_FAIL = 'ADD_TO_DEMAND_FAIL';
export const DEMAND_REMOVE_ITEM = 'DEMAND_REMOVE_ITEM';
export const DEMAND_RESET = 'DEMAND_RESET';