export const GET_NEW_BAGS = 'GET_NEW_BAGS';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';
export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';